[addresses]
integrator = "_"
rewards = "_"

[dependencies.EmojicoinDotFun]
local = "../emojicoin_dot_fun"

[dev-addresses]
coin_factory = "0xaaaa"
emojicoin_dot_fun = "0xc0de"
integrator = "0xccc"
rewards = "0xddd"

[dev-dependencies.BlackHeartCoinFactory]
local = "../test_coin_factories/black_heart"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "EmojicoinDotFunRewards"
upgrade_policy = "compatible"
version = "1.2.0"
