[addresses]
emojicoin_arena = "_"
integrator = "_"

[dependencies.EmojicoinDotFun]
local = "../emojicoin_dot_fun"

[dev-addresses]
coin_factory = "0xbbb"
emojicoin_arena = "0xaaa"
emojicoin_dot_fun = "0xc0de"
integrator = "0xddd"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "EmojicoinArena"
upgrade_policy = "compatible"
version = "1.0.0"
