[addresses]
coin_factory = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.EmojicoinDotFun]
local = "../emojicoin_dot_fun"

[dev-addresses]
coin_factory = "0xbbbbbbbb"
emojicoin_dot_fun = "0xcccccccc"

[package]
name = "CoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
