[addresses]
emojicoin_dot_fun = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
emojicoin_dot_fun = "0xc0de"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "EmojicoinDotFun"
upgrade_policy = "compatible"
version = "1.0.0"
